// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package training

import (
	"time"

	"github.com/google/uuid"
)

type TrainingBuilderDraft struct {
	UserID             uuid.UUID
	BlueprintVersion   string
	Position1Quantity  int16
	Position2Quantity  int16
	Position3Quantity  int16
	Position4Quantity  int16
	Position5Quantity  int16
	Position6Quantity  int16
	Position7Quantity  int16
	Position8Quantity  int16
	Position9Quantity  int16
	Position10Quantity int16
	Difficulty         string
	OnlyNew            bool
	Shuffle            bool
	PrioritizeMistakes bool
	Version            int64
	UpdatedAt          time.Time
}
