// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package training

import (
	"context"

	"github.com/google/uuid"
)

const createBuilderDraft = `-- name: CreateBuilderDraft :one
insert into training_builder_drafts (
    user_id,
    blueprint_version,
    position_1_quantity,
    position_2_quantity,
    position_3_quantity,
    position_4_quantity,
    position_5_quantity,
    position_6_quantity,
    position_7_quantity,
    position_8_quantity,
    position_9_quantity,
    position_10_quantity,
    difficulty,
    only_new,
    shuffle,
    prioritize_mistakes
)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
on conflict (user_id) do nothing
returning user_id, blueprint_version, position_1_quantity, position_2_quantity, position_3_quantity, position_4_quantity, position_5_quantity, position_6_quantity, position_7_quantity, position_8_quantity, position_9_quantity, position_10_quantity, difficulty, only_new, shuffle, prioritize_mistakes, version, updated_at
`

type CreateBuilderDraftParams struct {
	UserID             uuid.UUID
	BlueprintVersion   string
	Position1Quantity  int16
	Position2Quantity  int16
	Position3Quantity  int16
	Position4Quantity  int16
	Position5Quantity  int16
	Position6Quantity  int16
	Position7Quantity  int16
	Position8Quantity  int16
	Position9Quantity  int16
	Position10Quantity int16
	Difficulty         string
	OnlyNew            bool
	Shuffle            bool
	PrioritizeMistakes bool
}

func (q *Queries) CreateBuilderDraft(ctx context.Context, arg CreateBuilderDraftParams) (TrainingBuilderDraft, error) {
	row := q.db.QueryRow(ctx, createBuilderDraft,
		arg.UserID,
		arg.BlueprintVersion,
		arg.Position1Quantity,
		arg.Position2Quantity,
		arg.Position3Quantity,
		arg.Position4Quantity,
		arg.Position5Quantity,
		arg.Position6Quantity,
		arg.Position7Quantity,
		arg.Position8Quantity,
		arg.Position9Quantity,
		arg.Position10Quantity,
		arg.Difficulty,
		arg.OnlyNew,
		arg.Shuffle,
		arg.PrioritizeMistakes,
	)
	var i TrainingBuilderDraft
	err := row.Scan(
		&i.UserID,
		&i.BlueprintVersion,
		&i.Position1Quantity,
		&i.Position2Quantity,
		&i.Position3Quantity,
		&i.Position4Quantity,
		&i.Position5Quantity,
		&i.Position6Quantity,
		&i.Position7Quantity,
		&i.Position8Quantity,
		&i.Position9Quantity,
		&i.Position10Quantity,
		&i.Difficulty,
		&i.OnlyNew,
		&i.Shuffle,
		&i.PrioritizeMistakes,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getBuilderDraft = `-- name: GetBuilderDraft :one
select user_id, blueprint_version, position_1_quantity, position_2_quantity, position_3_quantity, position_4_quantity, position_5_quantity, position_6_quantity, position_7_quantity, position_8_quantity, position_9_quantity, position_10_quantity, difficulty, only_new, shuffle, prioritize_mistakes, version, updated_at
from training_builder_drafts
where user_id = $1
`

func (q *Queries) GetBuilderDraft(ctx context.Context, userID uuid.UUID) (TrainingBuilderDraft, error) {
	row := q.db.QueryRow(ctx, getBuilderDraft, userID)
	var i TrainingBuilderDraft
	err := row.Scan(
		&i.UserID,
		&i.BlueprintVersion,
		&i.Position1Quantity,
		&i.Position2Quantity,
		&i.Position3Quantity,
		&i.Position4Quantity,
		&i.Position5Quantity,
		&i.Position6Quantity,
		&i.Position7Quantity,
		&i.Position8Quantity,
		&i.Position9Quantity,
		&i.Position10Quantity,
		&i.Difficulty,
		&i.OnlyNew,
		&i.Shuffle,
		&i.PrioritizeMistakes,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBuilderDraft = `-- name: UpdateBuilderDraft :one
update training_builder_drafts
set blueprint_version = $1,
    position_1_quantity = $2,
    position_2_quantity = $3,
    position_3_quantity = $4,
    position_4_quantity = $5,
    position_5_quantity = $6,
    position_6_quantity = $7,
    position_7_quantity = $8,
    position_8_quantity = $9,
    position_9_quantity = $10,
    position_10_quantity = $11,
    difficulty = $12,
    only_new = $13,
    shuffle = $14,
    prioritize_mistakes = $15,
    version = version + 1,
    updated_at = now()
where user_id = $16
  and version = $17
  and version < 9223372036854775807
returning user_id, blueprint_version, position_1_quantity, position_2_quantity, position_3_quantity, position_4_quantity, position_5_quantity, position_6_quantity, position_7_quantity, position_8_quantity, position_9_quantity, position_10_quantity, difficulty, only_new, shuffle, prioritize_mistakes, version, updated_at
`

type UpdateBuilderDraftParams struct {
	BlueprintVersion   string
	Position1Quantity  int16
	Position2Quantity  int16
	Position3Quantity  int16
	Position4Quantity  int16
	Position5Quantity  int16
	Position6Quantity  int16
	Position7Quantity  int16
	Position8Quantity  int16
	Position9Quantity  int16
	Position10Quantity int16
	Difficulty         string
	OnlyNew            bool
	Shuffle            bool
	PrioritizeMistakes bool
	UserID             uuid.UUID
	ExpectedVersion    int64
}

func (q *Queries) UpdateBuilderDraft(ctx context.Context, arg UpdateBuilderDraftParams) (TrainingBuilderDraft, error) {
	row := q.db.QueryRow(ctx, updateBuilderDraft,
		arg.BlueprintVersion,
		arg.Position1Quantity,
		arg.Position2Quantity,
		arg.Position3Quantity,
		arg.Position4Quantity,
		arg.Position5Quantity,
		arg.Position6Quantity,
		arg.Position7Quantity,
		arg.Position8Quantity,
		arg.Position9Quantity,
		arg.Position10Quantity,
		arg.Difficulty,
		arg.OnlyNew,
		arg.Shuffle,
		arg.PrioritizeMistakes,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i TrainingBuilderDraft
	err := row.Scan(
		&i.UserID,
		&i.BlueprintVersion,
		&i.Position1Quantity,
		&i.Position2Quantity,
		&i.Position3Quantity,
		&i.Position4Quantity,
		&i.Position5Quantity,
		&i.Position6Quantity,
		&i.Position7Quantity,
		&i.Position8Quantity,
		&i.Position9Quantity,
		&i.Position10Quantity,
		&i.Difficulty,
		&i.OnlyNew,
		&i.Shuffle,
		&i.PrioritizeMistakes,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
