// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package progress

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type InsertAttemptsParams struct {
	UserID    uuid.UUID
	TaskID    string
	Slot      int32
	Correct   bool
	Source    string
	CreatedAt time.Time
}

const listAttempts = `-- name: ListAttempts :many
select task_id, slot, correct, source, created_at
from (
    select id, task_id, slot, correct, source, created_at
    from attempts
    where user_id = $1
    order by created_at desc, id desc
    limit 1000
) recent
order by created_at, id
`

type ListAttemptsRow struct {
	TaskID    string
	Slot      int32
	Correct   bool
	Source    string
	CreatedAt time.Time
}

func (q *Queries) ListAttempts(ctx context.Context, userID uuid.UUID) ([]ListAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listAttempts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttemptsRow
	for rows.Next() {
		var i ListAttemptsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Slot,
			&i.Correct,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
