// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package progress

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abandonRun = `-- name: AbandonRun :one
update runs
set status = 'abandoned',
    updated_at = now()
where id = $1 and user_id = $2 and status = 'active'
returning id, user_id, kind, status, blueprint_version, content_revision, started_at, deadline_at, submitted_at, duration_ms, created_at, updated_at
`

type AbandonRunParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) AbandonRun(ctx context.Context, arg AbandonRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, abandonRun, arg.ID, arg.UserID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.BlueprintVersion,
		&i.ContentRevision,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const canonicalizeSimulationDeadline = `-- name: CanonicalizeSimulationDeadline :one
update runs
set deadline_at = $1,
    updated_at = case
      when runs.deadline_at is null then now()
      else runs.updated_at
    end
where runs.id = $2
  and runs.user_id = $3
  and runs.kind = 'simulation'
  and (
    runs.deadline_at is null
    or runs.deadline_at = $1
  )
returning id, user_id, kind, status, blueprint_version, content_revision, started_at, deadline_at, submitted_at, duration_ms, created_at, updated_at
`

type CanonicalizeSimulationDeadlineParams struct {
	DeadlineAt pgtype.Timestamptz
	ID         uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) CanonicalizeSimulationDeadline(ctx context.Context, arg CanonicalizeSimulationDeadlineParams) (Run, error) {
	row := q.db.QueryRow(ctx, canonicalizeSimulationDeadline, arg.DeadlineAt, arg.ID, arg.UserID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.BlueprintVersion,
		&i.ContentRevision,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttempt = `-- name: CreateAttempt :one
insert into attempts (
    public_id,
    user_id,
    run_item_id,
    task_id,
    slot,
    correct,
    source,
    help_level,
    created_at,
    started_at,
    submitted_at,
    active_duration_ms,
    answer,
    outcome,
    grading_kind,
    earned_points,
    max_points,
    task_revision
)
values (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17, $18
)
on conflict (public_id) do nothing
returning id, user_id, task_id, slot, correct, source, created_at, help_level, public_id, run_item_id, started_at, submitted_at, active_duration_ms, answer, outcome, grading_kind, earned_points, max_points, task_revision
`

type CreateAttemptParams struct {
	PublicID         uuid.UUID
	UserID           uuid.UUID
	RunItemID        pgtype.UUID
	TaskID           string
	Slot             int32
	Correct          bool
	Source           string
	HelpLevel        int16
	CreatedAt        time.Time
	StartedAt        pgtype.Timestamptz
	SubmittedAt      pgtype.Timestamptz
	ActiveDurationMs *int64
	Answer           *string
	Outcome          *string
	GradingKind      *string
	EarnedPoints     *int16
	MaxPoints        *int16
	TaskRevision     *string
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.PublicID,
		arg.UserID,
		arg.RunItemID,
		arg.TaskID,
		arg.Slot,
		arg.Correct,
		arg.Source,
		arg.HelpLevel,
		arg.CreatedAt,
		arg.StartedAt,
		arg.SubmittedAt,
		arg.ActiveDurationMs,
		arg.Answer,
		arg.Outcome,
		arg.GradingKind,
		arg.EarnedPoints,
		arg.MaxPoints,
		arg.TaskRevision,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Slot,
		&i.Correct,
		&i.Source,
		&i.CreatedAt,
		&i.HelpLevel,
		&i.PublicID,
		&i.RunItemID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.ActiveDurationMs,
		&i.Answer,
		&i.Outcome,
		&i.GradingKind,
		&i.EarnedPoints,
		&i.MaxPoints,
		&i.TaskRevision,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
insert into runs (
    id,
    user_id,
    kind,
    blueprint_version,
    content_revision,
    started_at,
    deadline_at
)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (id) do nothing
returning id, user_id, kind, status, blueprint_version, content_revision, started_at, deadline_at, submitted_at, duration_ms, created_at, updated_at
`

type CreateRunParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Kind             string
	BlueprintVersion string
	ContentRevision  string
	StartedAt        time.Time
	DeadlineAt       pgtype.Timestamptz
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.BlueprintVersion,
		arg.ContentRevision,
		arg.StartedAt,
		arg.DeadlineAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.BlueprintVersion,
		&i.ContentRevision,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRunCheckpoint = `-- name: CreateRunCheckpoint :one
insert into run_checkpoints (
    run_id,
    user_id,
    version,
    current_ordinal,
    active_duration_ms
)
values ($1, $2, 1, $3, $4)
returning run_id, user_id, version, current_ordinal, active_duration_ms, updated_at
`

type CreateRunCheckpointParams struct {
	RunID            uuid.UUID
	UserID           uuid.UUID
	CurrentOrdinal   int16
	ActiveDurationMs *int64
}

func (q *Queries) CreateRunCheckpoint(ctx context.Context, arg CreateRunCheckpointParams) (RunCheckpoint, error) {
	row := q.db.QueryRow(ctx, createRunCheckpoint,
		arg.RunID,
		arg.UserID,
		arg.CurrentOrdinal,
		arg.ActiveDurationMs,
	)
	var i RunCheckpoint
	err := row.Scan(
		&i.RunID,
		&i.UserID,
		&i.Version,
		&i.CurrentOrdinal,
		&i.ActiveDurationMs,
		&i.UpdatedAt,
	)
	return i, err
}

const createRunCheckpointDraft = `-- name: CreateRunCheckpointDraft :one
insert into run_checkpoint_drafts (run_id, run_item_id, user_id, answer)
values ($1, $2, $3, $4)
returning run_id, run_item_id, user_id, answer
`

type CreateRunCheckpointDraftParams struct {
	RunID     uuid.UUID
	RunItemID uuid.UUID
	UserID    uuid.UUID
	Answer    string
}

func (q *Queries) CreateRunCheckpointDraft(ctx context.Context, arg CreateRunCheckpointDraftParams) (RunCheckpointDraft, error) {
	row := q.db.QueryRow(ctx, createRunCheckpointDraft,
		arg.RunID,
		arg.RunItemID,
		arg.UserID,
		arg.Answer,
	)
	var i RunCheckpointDraft
	err := row.Scan(
		&i.RunID,
		&i.RunItemID,
		&i.UserID,
		&i.Answer,
	)
	return i, err
}

const createRunItem = `-- name: CreateRunItem :one
insert into run_items (
    id,
    run_id,
    user_id,
    task_id,
    ordinal,
    exam_position,
    topic,
    max_points,
    task_revision
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, run_id, user_id, task_id, ordinal, exam_position, topic, max_points, task_revision, created_at
`

type CreateRunItemParams struct {
	ID           uuid.UUID
	RunID        uuid.UUID
	UserID       uuid.UUID
	TaskID       string
	Ordinal      int16
	ExamPosition int16
	Topic        string
	MaxPoints    *int16
	TaskRevision string
}

func (q *Queries) CreateRunItem(ctx context.Context, arg CreateRunItemParams) (RunItem, error) {
	row := q.db.QueryRow(ctx, createRunItem,
		arg.ID,
		arg.RunID,
		arg.UserID,
		arg.TaskID,
		arg.Ordinal,
		arg.ExamPosition,
		arg.Topic,
		arg.MaxPoints,
		arg.TaskRevision,
	)
	var i RunItem
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.UserID,
		&i.TaskID,
		&i.Ordinal,
		&i.ExamPosition,
		&i.Topic,
		&i.MaxPoints,
		&i.TaskRevision,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRunCheckpoint = `-- name: DeleteRunCheckpoint :exec
delete from run_checkpoints
where run_id = $1 and user_id = $2
`

type DeleteRunCheckpointParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteRunCheckpoint(ctx context.Context, arg DeleteRunCheckpointParams) error {
	_, err := q.db.Exec(ctx, deleteRunCheckpoint, arg.RunID, arg.UserID)
	return err
}

const deleteRunCheckpointDrafts = `-- name: DeleteRunCheckpointDrafts :exec
delete from run_checkpoint_drafts
where run_id = $1 and user_id = $2
`

type DeleteRunCheckpointDraftsParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteRunCheckpointDrafts(ctx context.Context, arg DeleteRunCheckpointDraftsParams) error {
	_, err := q.db.Exec(ctx, deleteRunCheckpointDrafts, arg.RunID, arg.UserID)
	return err
}

const getAttempt = `-- name: GetAttempt :one
select id, user_id, task_id, slot, correct, source, created_at, help_level, public_id, run_item_id, started_at, submitted_at, active_duration_ms, answer, outcome, grading_kind, earned_points, max_points, task_revision
from attempts
where public_id = $1 and user_id = $2
`

type GetAttemptParams struct {
	PublicID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetAttempt(ctx context.Context, arg GetAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, arg.PublicID, arg.UserID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Slot,
		&i.Correct,
		&i.Source,
		&i.CreatedAt,
		&i.HelpLevel,
		&i.PublicID,
		&i.RunItemID,
		&i.StartedAt,
		&i.SubmittedAt,
		&i.ActiveDurationMs,
		&i.Answer,
		&i.Outcome,
		&i.GradingKind,
		&i.EarnedPoints,
		&i.MaxPoints,
		&i.TaskRevision,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
select id, user_id, kind, status, blueprint_version, content_revision, started_at, deadline_at, submitted_at, duration_ms, created_at, updated_at
from runs
where id = $1 and user_id = $2
`

type GetRunParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, arg.ID, arg.UserID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.BlueprintVersion,
		&i.ContentRevision,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunCheckpointForUpdate = `-- name: GetRunCheckpointForUpdate :one
select run_id, user_id, version, current_ordinal, active_duration_ms, updated_at
from run_checkpoints
where run_id = $1 and user_id = $2
for update
`

type GetRunCheckpointForUpdateParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRunCheckpointForUpdate(ctx context.Context, arg GetRunCheckpointForUpdateParams) (RunCheckpoint, error) {
	row := q.db.QueryRow(ctx, getRunCheckpointForUpdate, arg.RunID, arg.UserID)
	var i RunCheckpoint
	err := row.Scan(
		&i.RunID,
		&i.UserID,
		&i.Version,
		&i.CurrentOrdinal,
		&i.ActiveDurationMs,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
select id, user_id, kind, status, blueprint_version, content_revision, started_at, deadline_at, submitted_at, duration_ms, created_at, updated_at
from runs
where id = $1 and user_id = $2
for update
`

type GetRunForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRunForUpdate(ctx context.Context, arg GetRunForUpdateParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunForUpdate, arg.ID, arg.UserID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.BlueprintVersion,
		&i.ContentRevision,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunItemTarget = `-- name: GetRunItemTarget :one
select
    i.id,
    i.run_id,
    i.task_id,
    i.exam_position,
    i.max_points as item_max_points,
    i.task_revision,
    r.kind as run_kind,
    r.status as run_status,
    r.started_at as run_started_at
from run_items i
join runs r on r.id = i.run_id and r.user_id = i.user_id
where i.id = $1 and i.user_id = $2
for share of r
`

type GetRunItemTargetParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetRunItemTargetRow struct {
	ID            uuid.UUID
	RunID         uuid.UUID
	TaskID        string
	ExamPosition  int16
	ItemMaxPoints *int16
	TaskRevision  string
	RunKind       string
	RunStatus     string
	RunStartedAt  time.Time
}

func (q *Queries) GetRunItemTarget(ctx context.Context, arg GetRunItemTargetParams) (GetRunItemTargetRow, error) {
	row := q.db.QueryRow(ctx, getRunItemTarget, arg.ID, arg.UserID)
	var i GetRunItemTargetRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TaskID,
		&i.ExamPosition,
		&i.ItemMaxPoints,
		&i.TaskRevision,
		&i.RunKind,
		&i.RunStatus,
		&i.RunStartedAt,
	)
	return i, err
}

type InsertAttemptsParams struct {
	UserID      uuid.UUID
	TaskID      string
	Slot        int32
	Correct     bool
	Source      string
	HelpLevel   int16
	CreatedAt   time.Time
	StartedAt   pgtype.Timestamptz
	SubmittedAt pgtype.Timestamptz
	Outcome     *string
	GradingKind *string
}

const listAttemptJournal = `-- name: ListAttemptJournal :many
with recent_attempt_ids as (
    select id
    from attempts
    where attempts.user_id = $1
    order by coalesce(submitted_at, created_at) desc, id desc
    limit $2
)
select a.id, a.user_id, a.task_id, a.slot, a.correct, a.source, a.created_at, a.help_level, a.public_id, a.run_item_id, a.started_at, a.submitted_at, a.active_duration_ms, a.answer, a.outcome, a.grading_kind, a.earned_points, a.max_points, a.task_revision
from attempts a
join recent_attempt_ids recent on recent.id = a.id
order by coalesce(a.submitted_at, a.created_at), a.id
`

type ListAttemptJournalParams struct {
	UserID      uuid.UUID
	MaxAttempts int32
}

func (q *Queries) ListAttemptJournal(ctx context.Context, arg ListAttemptJournalParams) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listAttemptJournal, arg.UserID, arg.MaxAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Slot,
			&i.Correct,
			&i.Source,
			&i.CreatedAt,
			&i.HelpLevel,
			&i.PublicID,
			&i.RunItemID,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.ActiveDurationMs,
			&i.Answer,
			&i.Outcome,
			&i.GradingKind,
			&i.EarnedPoints,
			&i.MaxPoints,
			&i.TaskRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttempts = `-- name: ListAttempts :many
select task_id, slot, correct, source, help_level, created_at
from (
    select id, task_id, slot, correct, source, help_level, created_at
    from attempts
    where user_id = $1
      and (outcome is null or outcome in ('correct', 'incorrect'))
    order by created_at desc, id desc
    limit 1000
) recent
order by created_at, id
`

type ListAttemptsRow struct {
	TaskID    string
	Slot      int32
	Correct   bool
	Source    string
	HelpLevel int16
	CreatedAt time.Time
}

func (q *Queries) ListAttempts(ctx context.Context, userID uuid.UUID) ([]ListAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listAttempts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttemptsRow
	for rows.Next() {
		var i ListAttemptsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.Slot,
			&i.Correct,
			&i.Source,
			&i.HelpLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedSimulationRuns = `-- name: ListCompletedSimulationRuns :many
select runs.id, runs.user_id, runs.kind, runs.status, runs.blueprint_version, runs.content_revision, runs.started_at, runs.deadline_at, runs.submitted_at, runs.duration_ms, runs.created_at, runs.updated_at
from runs
where runs.user_id = $1
  and runs.kind = 'simulation'
  and runs.status = 'submitted'
  and runs.blueprint_version ~ '^ftn-p1:[0-9]{4}[.][0-9]+$'
  and runs.content_revision ~ '^sha256:[a-f0-9]{64}$'
  and runs.duration_ms between 0 and 4 * 60 * 60 * 1000
  and (
    runs.deadline_at is null
    or runs.deadline_at = runs.started_at + interval '4 hours'
  )
  and exists (
    select 1
    from run_items
    where run_items.run_id = runs.id
      and run_items.user_id = runs.user_id
    group by run_items.run_id, run_items.user_id
    having count(*) = 10
      and count(run_items.max_points) = 10
      and min(run_items.ordinal) = 1
      and max(run_items.ordinal) = 10
      and count(distinct run_items.exam_position) = 10
      and bool_and(run_items.ordinal = run_items.exam_position)
      and min(run_items.max_points) >= 1
      and sum(run_items.max_points) = 60
      and bool_and(run_items.task_revision ~ '^sha256:[a-f0-9]{64}$')
  )
  and not exists (
    select 1
    from attempts
    join run_items on run_items.id = attempts.run_item_id
      and run_items.user_id = attempts.user_id
    where run_items.run_id = runs.id
      and attempts.user_id = runs.user_id
      and (
        attempts.started_at is null
        or attempts.submitted_at is null
        or attempts.started_at < runs.started_at
        or attempts.submitted_at > runs.submitted_at
      )
  )
order by runs.submitted_at desc, runs.id
limit $2
`

type ListCompletedSimulationRunsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListCompletedSimulationRuns(ctx context.Context, arg ListCompletedSimulationRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listCompletedSimulationRuns, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Status,
			&i.BlueprintVersion,
			&i.ContentRevision,
			&i.StartedAt,
			&i.DeadlineAt,
			&i.SubmittedAt,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestRunAttemptsByRunIDs = `-- name: ListLatestRunAttemptsByRunIDs :many
with ranked_attempt_ids as (
    select
        a.id,
        row_number() over (
            partition by a.run_item_id
            order by coalesce(a.submitted_at, a.created_at) desc, a.id desc
        ) as attempt_rank
    from attempts a
    join run_items i on i.id = a.run_item_id and i.user_id = a.user_id
    where i.run_id = any($1::uuid[])
      and a.user_id = $2
)
select a.id, a.user_id, a.task_id, a.slot, a.correct, a.source, a.created_at, a.help_level, a.public_id, a.run_item_id, a.started_at, a.submitted_at, a.active_duration_ms, a.answer, a.outcome, a.grading_kind, a.earned_points, a.max_points, a.task_revision
from attempts a
join ranked_attempt_ids latest on latest.id = a.id
where latest.attempt_rank = 1
order by coalesce(a.submitted_at, a.created_at), a.id
`

type ListLatestRunAttemptsByRunIDsParams struct {
	RunIds []uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListLatestRunAttemptsByRunIDs(ctx context.Context, arg ListLatestRunAttemptsByRunIDsParams) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listLatestRunAttemptsByRunIDs, arg.RunIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Slot,
			&i.Correct,
			&i.Source,
			&i.CreatedAt,
			&i.HelpLevel,
			&i.PublicID,
			&i.RunItemID,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.ActiveDurationMs,
			&i.Answer,
			&i.Outcome,
			&i.GradingKind,
			&i.EarnedPoints,
			&i.MaxPoints,
			&i.TaskRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunAttempts = `-- name: ListRunAttempts :many
with ranked_attempt_ids as (
    select
        a.id,
        row_number() over (
            partition by a.run_item_id
            order by coalesce(a.submitted_at, a.created_at) desc, a.id desc
        ) as attempt_rank
    from attempts a
    join run_items i on i.id = a.run_item_id and i.user_id = a.user_id
    where i.run_id = $2 and a.user_id = $3
)
select a.id, a.user_id, a.task_id, a.slot, a.correct, a.source, a.created_at, a.help_level, a.public_id, a.run_item_id, a.started_at, a.submitted_at, a.active_duration_ms, a.answer, a.outcome, a.grading_kind, a.earned_points, a.max_points, a.task_revision
from attempts a
join ranked_attempt_ids recent on recent.id = a.id
where recent.attempt_rank <= $1::integer
order by coalesce(a.submitted_at, a.created_at), a.id
`

type ListRunAttemptsParams struct {
	MaxAttempts int32
	RunID       uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) ListRunAttempts(ctx context.Context, arg ListRunAttemptsParams) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listRunAttempts, arg.MaxAttempts, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Slot,
			&i.Correct,
			&i.Source,
			&i.CreatedAt,
			&i.HelpLevel,
			&i.PublicID,
			&i.RunItemID,
			&i.StartedAt,
			&i.SubmittedAt,
			&i.ActiveDurationMs,
			&i.Answer,
			&i.Outcome,
			&i.GradingKind,
			&i.EarnedPoints,
			&i.MaxPoints,
			&i.TaskRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunCheckpointDrafts = `-- name: ListRunCheckpointDrafts :many
select draft.run_id, draft.run_item_id, draft.user_id, draft.answer
from run_checkpoint_drafts draft
join run_items item
  on item.run_id = draft.run_id
 and item.id = draft.run_item_id
 and item.user_id = draft.user_id
where draft.run_id = $1 and draft.user_id = $2
order by item.ordinal
`

type ListRunCheckpointDraftsParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListRunCheckpointDrafts(ctx context.Context, arg ListRunCheckpointDraftsParams) ([]RunCheckpointDraft, error) {
	rows, err := q.db.Query(ctx, listRunCheckpointDrafts, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunCheckpointDraft
	for rows.Next() {
		var i RunCheckpointDraft
		if err := rows.Scan(
			&i.RunID,
			&i.RunItemID,
			&i.UserID,
			&i.Answer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunCheckpointRows = `-- name: ListRunCheckpointRows :many
select checkpoint.run_id,
       checkpoint.user_id,
       checkpoint.version,
       checkpoint.current_ordinal,
       checkpoint.active_duration_ms,
       checkpoint.updated_at,
       draft.run_item_id,
       draft.answer
from run_checkpoints checkpoint
left join run_checkpoint_drafts draft
  on draft.run_id = checkpoint.run_id
 and draft.user_id = checkpoint.user_id
left join run_items item
  on item.run_id = draft.run_id
 and item.id = draft.run_item_id
 and item.user_id = draft.user_id
where checkpoint.run_id = $1 and checkpoint.user_id = $2
order by item.ordinal nulls last
`

type ListRunCheckpointRowsParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

type ListRunCheckpointRowsRow struct {
	RunID            uuid.UUID
	UserID           uuid.UUID
	Version          int64
	CurrentOrdinal   int16
	ActiveDurationMs *int64
	UpdatedAt        time.Time
	RunItemID        pgtype.UUID
	Answer           *string
}

func (q *Queries) ListRunCheckpointRows(ctx context.Context, arg ListRunCheckpointRowsParams) ([]ListRunCheckpointRowsRow, error) {
	rows, err := q.db.Query(ctx, listRunCheckpointRows, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunCheckpointRowsRow
	for rows.Next() {
		var i ListRunCheckpointRowsRow
		if err := rows.Scan(
			&i.RunID,
			&i.UserID,
			&i.Version,
			&i.CurrentOrdinal,
			&i.ActiveDurationMs,
			&i.UpdatedAt,
			&i.RunItemID,
			&i.Answer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunItems = `-- name: ListRunItems :many
select id, run_id, user_id, task_id, ordinal, exam_position, topic, max_points, task_revision, created_at
from run_items
where run_id = $1 and user_id = $2
order by ordinal
`

type ListRunItemsParams struct {
	RunID  uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListRunItems(ctx context.Context, arg ListRunItemsParams) ([]RunItem, error) {
	rows, err := q.db.Query(ctx, listRunItems, arg.RunID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunItem
	for rows.Next() {
		var i RunItem
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.UserID,
			&i.TaskID,
			&i.Ordinal,
			&i.ExamPosition,
			&i.Topic,
			&i.MaxPoints,
			&i.TaskRevision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunItemsByRunIDs = `-- name: ListRunItemsByRunIDs :many
select id, run_id, user_id, task_id, ordinal, exam_position, topic, max_points, task_revision, created_at
from run_items
where user_id = $1
  and run_id = any($2::uuid[])
order by run_id, ordinal
`

type ListRunItemsByRunIDsParams struct {
	UserID uuid.UUID
	RunIds []uuid.UUID
}

func (q *Queries) ListRunItemsByRunIDs(ctx context.Context, arg ListRunItemsByRunIDsParams) ([]RunItem, error) {
	rows, err := q.db.Query(ctx, listRunItemsByRunIDs, arg.UserID, arg.RunIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunItem
	for rows.Next() {
		var i RunItem
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.UserID,
			&i.TaskID,
			&i.Ordinal,
			&i.ExamPosition,
			&i.Topic,
			&i.MaxPoints,
			&i.TaskRevision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
select id, user_id, kind, status, blueprint_version, content_revision, started_at, deadline_at, submitted_at, duration_ms, created_at, updated_at
from runs
where user_id = $1
order by started_at desc, id
limit $2
`

type ListRunsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Status,
			&i.BlueprintVersion,
			&i.ContentRevision,
			&i.StartedAt,
			&i.DeadlineAt,
			&i.SubmittedAt,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runHasAttemptAfter = `-- name: RunHasAttemptAfter :one
select exists (
    select 1
    from attempts a
    join run_items i on i.id = a.run_item_id and i.user_id = a.user_id
    where i.run_id = $1
      and a.user_id = $2
      and coalesce(a.submitted_at, a.created_at) > $3
)
`

type RunHasAttemptAfterParams struct {
	RunID       uuid.UUID
	UserID      uuid.UUID
	SubmittedAt pgtype.Timestamptz
}

func (q *Queries) RunHasAttemptAfter(ctx context.Context, arg RunHasAttemptAfterParams) (bool, error) {
	row := q.db.QueryRow(ctx, runHasAttemptAfter, arg.RunID, arg.UserID, arg.SubmittedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const submitRun = `-- name: SubmitRun :one
update runs
set status = 'submitted',
    submitted_at = $3,
    duration_ms = $4,
    updated_at = now()
where id = $1 and user_id = $2 and status = 'active'
returning id, user_id, kind, status, blueprint_version, content_revision, started_at, deadline_at, submitted_at, duration_ms, created_at, updated_at
`

type SubmitRunParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	SubmittedAt pgtype.Timestamptz
	DurationMs  *int64
}

func (q *Queries) SubmitRun(ctx context.Context, arg SubmitRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, submitRun,
		arg.ID,
		arg.UserID,
		arg.SubmittedAt,
		arg.DurationMs,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.BlueprintVersion,
		&i.ContentRevision,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.SubmittedAt,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchRun = `-- name: TouchRun :exec
update runs
set updated_at = now()
where id = $1 and user_id = $2
`

type TouchRunParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) TouchRun(ctx context.Context, arg TouchRunParams) error {
	_, err := q.db.Exec(ctx, touchRun, arg.ID, arg.UserID)
	return err
}

const updateRunCheckpoint = `-- name: UpdateRunCheckpoint :one
update run_checkpoints
set version = version + 1,
    current_ordinal = $4,
    active_duration_ms = $5,
    updated_at = now()
where run_id = $1 and user_id = $2 and version = $3
returning run_id, user_id, version, current_ordinal, active_duration_ms, updated_at
`

type UpdateRunCheckpointParams struct {
	RunID            uuid.UUID
	UserID           uuid.UUID
	Version          int64
	CurrentOrdinal   int16
	ActiveDurationMs *int64
}

func (q *Queries) UpdateRunCheckpoint(ctx context.Context, arg UpdateRunCheckpointParams) (RunCheckpoint, error) {
	row := q.db.QueryRow(ctx, updateRunCheckpoint,
		arg.RunID,
		arg.UserID,
		arg.Version,
		arg.CurrentOrdinal,
		arg.ActiveDurationMs,
	)
	var i RunCheckpoint
	err := row.Scan(
		&i.RunID,
		&i.UserID,
		&i.Version,
		&i.CurrentOrdinal,
		&i.ActiveDurationMs,
		&i.UpdatedAt,
	)
	return i, err
}
