// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AbandonRunInput struct {
	ID string `json:"id"`
}

type Attempt struct {
	ID               string         `json:"id"`
	RunItemID        *string        `json:"runItemId,omitempty"`
	TaskID           string         `json:"taskId"`
	ExamPosition     int32          `json:"examPosition"`
	Mode             RunKind        `json:"mode"`
	StartedAt        time.Time      `json:"startedAt"`
	SubmittedAt      time.Time      `json:"submittedAt"`
	ActiveDurationMs *int64         `json:"activeDurationMs,omitempty"`
	Answer           *string        `json:"answer,omitempty"`
	Outcome          AttemptOutcome `json:"outcome"`
	HelpLevel        int32          `json:"helpLevel"`
	GradingKind      GradingKind    `json:"gradingKind"`
	EarnedPoints     *int32         `json:"earnedPoints,omitempty"`
	MaxPoints        *int32         `json:"maxPoints,omitempty"`
	TaskRevision     *string        `json:"taskRevision,omitempty"`
}

type CheckpointRunInput struct {
	ID string `json:"id"`
	// Use zero for the first write, then the version returned by the server.
	ExpectedVersion  int64  `json:"expectedVersion"`
	CurrentOrdinal   int32  `json:"currentOrdinal"`
	ActiveDurationMs *int64 `json:"activeDurationMs,omitempty"`
	// Full draft replacement; omitting an item removes its previous draft.
	Drafts []RunCheckpointDraftInput `json:"drafts"`
}

type CompletedSimulationRun struct {
	ID               string                       `json:"id"`
	BlueprintVersion string                       `json:"blueprintVersion"`
	ContentRevision  string                       `json:"contentRevision"`
	StartedAt        time.Time                    `json:"startedAt"`
	DeadlineAt       *time.Time                   `json:"deadlineAt,omitempty"`
	SubmittedAt      time.Time                    `json:"submittedAt"`
	ActiveDurationMs *int64                       `json:"activeDurationMs,omitempty"`
	Items            []CompletedSimulationRunItem `json:"items"`
}

type CompletedSimulationRunItem struct {
	TaskID          string          `json:"taskId"`
	ExamPosition    int32           `json:"examPosition"`
	Topic           string          `json:"topic"`
	MaxPoints       *int32          `json:"maxPoints,omitempty"`
	AnswerPartCount *int32          `json:"answerPartCount,omitempty"`
	TaskRevision    string          `json:"taskRevision"`
	Answer          *string         `json:"answer,omitempty"`
	Outcome         *AttemptOutcome `json:"outcome,omitempty"`
	GradingKind     *GradingKind    `json:"gradingKind,omitempty"`
	EarnedPoints    *int32          `json:"earnedPoints,omitempty"`
}

type Mutation struct {
}

type NewRunItemInput struct {
	ID              string `json:"id"`
	TaskID          string `json:"taskId"`
	ExamPosition    int32  `json:"examPosition"`
	Topic           string `json:"topic"`
	MaxPoints       *int32 `json:"maxPoints,omitempty"`
	AnswerPartCount *int32 `json:"answerPartCount,omitempty"`
	TaskRevision    string `json:"taskRevision"`
}

type Query struct {
}

type RecordAttemptInput struct {
	ID               string                        `json:"id"`
	RunItemID        *string                       `json:"runItemId,omitempty"`
	Standalone       *StandaloneAttemptTargetInput `json:"standalone,omitempty"`
	StartedAt        time.Time                     `json:"startedAt"`
	SubmittedAt      time.Time                     `json:"submittedAt"`
	ActiveDurationMs *int64                        `json:"activeDurationMs,omitempty"`
	Answer           *string                       `json:"answer,omitempty"`
	Outcome          AttemptOutcome                `json:"outcome"`
	HelpLevel        int32                         `json:"helpLevel"`
	GradingKind      ClientGradingKind             `json:"gradingKind"`
	EarnedPoints     *int32                        `json:"earnedPoints,omitempty"`
}

type Run struct {
	ID               string     `json:"id"`
	Kind             RunKind    `json:"kind"`
	Status           RunStatus  `json:"status"`
	BlueprintVersion string     `json:"blueprintVersion"`
	ContentRevision  string     `json:"contentRevision"`
	StartedAt        time.Time  `json:"startedAt"`
	DeadlineAt       *time.Time `json:"deadlineAt,omitempty"`
	SubmittedAt      *time.Time `json:"submittedAt,omitempty"`
	ActiveDurationMs *int64     `json:"activeDurationMs,omitempty"`
	// Mutable active state; absent after submit or abandon.
	Checkpoint *RunCheckpoint `json:"checkpoint,omitempty"`
	Items      []RunItem      `json:"items"`
}

type RunCheckpoint struct {
	Version          int64                `json:"version"`
	CurrentOrdinal   int32                `json:"currentOrdinal"`
	ActiveDurationMs *int64               `json:"activeDurationMs,omitempty"`
	UpdatedAt        time.Time            `json:"updatedAt"`
	Drafts           []RunCheckpointDraft `json:"drafts"`
}

type RunCheckpointDraft struct {
	RunItemID string `json:"runItemId"`
	Answer    string `json:"answer"`
}

type RunCheckpointDraftInput struct {
	RunItemID string `json:"runItemId"`
	Answer    string `json:"answer"`
}

type RunItem struct {
	ID              string `json:"id"`
	TaskID          string `json:"taskId"`
	Ordinal         int32  `json:"ordinal"`
	ExamPosition    int32  `json:"examPosition"`
	Topic           string `json:"topic"`
	MaxPoints       *int32 `json:"maxPoints,omitempty"`
	AnswerPartCount *int32 `json:"answerPartCount,omitempty"`
	TaskRevision    string `json:"taskRevision"`
	// Returns the latest attempts in chronological order, up to a limit of 20.
	RecentAttempts []Attempt `json:"recentAttempts"`
}

type RunSummary struct {
	ID                 string     `json:"id"`
	Kind               RunKind    `json:"kind"`
	Status             RunStatus  `json:"status"`
	BlueprintVersion   string     `json:"blueprintVersion"`
	ContentRevision    string     `json:"contentRevision"`
	StartedAt          time.Time  `json:"startedAt"`
	DeadlineAt         *time.Time `json:"deadlineAt,omitempty"`
	SubmittedAt        *time.Time `json:"submittedAt,omitempty"`
	ActiveDurationMs   *int64     `json:"activeDurationMs,omitempty"`
	TaskIds            []string   `json:"taskIds"`
	ItemCount          int32      `json:"itemCount"`
	CompletedItemCount int32      `json:"completedItemCount"`
	CorrectItemCount   int32      `json:"correctItemCount"`
	EarnedPoints       *int32     `json:"earnedPoints,omitempty"`
	MaxPoints          *int32     `json:"maxPoints,omitempty"`
}

type StandaloneAttemptTargetInput struct {
	TaskID       string `json:"taskId"`
	ExamPosition int32  `json:"examPosition"`
	TaskRevision string `json:"taskRevision"`
	MaxPoints    *int32 `json:"maxPoints,omitempty"`
}

type StartRunInput struct {
	ID               string            `json:"id"`
	Kind             RunKind           `json:"kind"`
	BlueprintVersion string            `json:"blueprintVersion"`
	ContentRevision  string            `json:"contentRevision"`
	StartedAt        time.Time         `json:"startedAt"`
	DeadlineAt       *time.Time        `json:"deadlineAt,omitempty"`
	Items            []NewRunItemInput `json:"items"`
}

type SubmitRunInput struct {
	ID               string    `json:"id"`
	SubmittedAt      time.Time `json:"submittedAt"`
	ActiveDurationMs *int64    `json:"activeDurationMs,omitempty"`
}

type AttemptOutcome string

const (
	AttemptOutcomeCorrect   AttemptOutcome = "CORRECT"
	AttemptOutcomeIncorrect AttemptOutcome = "INCORRECT"
	AttemptOutcomePartial   AttemptOutcome = "PARTIAL"
	AttemptOutcomeSkipped   AttemptOutcome = "SKIPPED"
	AttemptOutcomeUngraded  AttemptOutcome = "UNGRADED"
)

var AllAttemptOutcome = []AttemptOutcome{
	AttemptOutcomeCorrect,
	AttemptOutcomeIncorrect,
	AttemptOutcomePartial,
	AttemptOutcomeSkipped,
	AttemptOutcomeUngraded,
}

func (e AttemptOutcome) IsValid() bool {
	switch e {
	case AttemptOutcomeCorrect, AttemptOutcomeIncorrect, AttemptOutcomePartial, AttemptOutcomeSkipped, AttemptOutcomeUngraded:
		return true
	}
	return false
}

func (e AttemptOutcome) String() string {
	return string(e)
}

func (e *AttemptOutcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AttemptOutcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AttemptOutcome", str)
	}
	return nil
}

func (e AttemptOutcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AttemptOutcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AttemptOutcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ClientGradingKind string

const (
	ClientGradingKindAuto       ClientGradingKind = "AUTO"
	ClientGradingKindRubricSelf ClientGradingKind = "RUBRIC_SELF"
)

var AllClientGradingKind = []ClientGradingKind{
	ClientGradingKindAuto,
	ClientGradingKindRubricSelf,
}

func (e ClientGradingKind) IsValid() bool {
	switch e {
	case ClientGradingKindAuto, ClientGradingKindRubricSelf:
		return true
	}
	return false
}

func (e ClientGradingKind) String() string {
	return string(e)
}

func (e *ClientGradingKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClientGradingKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClientGradingKind", str)
	}
	return nil
}

func (e ClientGradingKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClientGradingKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClientGradingKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GradingKind string

const (
	GradingKindAuto       GradingKind = "AUTO"
	GradingKindRubricSelf GradingKind = "RUBRIC_SELF"
	GradingKindAiAssisted GradingKind = "AI_ASSISTED"
	GradingKindHuman      GradingKind = "HUMAN"
)

var AllGradingKind = []GradingKind{
	GradingKindAuto,
	GradingKindRubricSelf,
	GradingKindAiAssisted,
	GradingKindHuman,
}

func (e GradingKind) IsValid() bool {
	switch e {
	case GradingKindAuto, GradingKindRubricSelf, GradingKindAiAssisted, GradingKindHuman:
		return true
	}
	return false
}

func (e GradingKind) String() string {
	return string(e)
}

func (e *GradingKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GradingKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GradingKind", str)
	}
	return nil
}

func (e GradingKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GradingKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GradingKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RunKind string

const (
	RunKindPractice   RunKind = "PRACTICE"
	RunKindDiagnostic RunKind = "DIAGNOSTIC"
	RunKindSimulation RunKind = "SIMULATION"
)

var AllRunKind = []RunKind{
	RunKindPractice,
	RunKindDiagnostic,
	RunKindSimulation,
}

func (e RunKind) IsValid() bool {
	switch e {
	case RunKindPractice, RunKindDiagnostic, RunKindSimulation:
		return true
	}
	return false
}

func (e RunKind) String() string {
	return string(e)
}

func (e *RunKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RunKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RunKind", str)
	}
	return nil
}

func (e RunKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RunKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RunKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RunStatus string

const (
	RunStatusActive    RunStatus = "ACTIVE"
	RunStatusSubmitted RunStatus = "SUBMITTED"
	RunStatusAbandoned RunStatus = "ABANDONED"
)

var AllRunStatus = []RunStatus{
	RunStatusActive,
	RunStatusSubmitted,
	RunStatusAbandoned,
}

func (e RunStatus) IsValid() bool {
	switch e {
	case RunStatusActive, RunStatusSubmitted, RunStatusAbandoned:
		return true
	}
	return false
}

func (e RunStatus) String() string {
	return string(e)
}

func (e *RunStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RunStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RunStatus", str)
	}
	return nil
}

func (e RunStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RunStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RunStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
