// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"time"

	"github.com/google/uuid"
)

type AuthCode struct {
	CodeHash  []byte
	UserID    uuid.UUID
	Redirect  string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID         uuid.UUID
	GoogleSub  string
	Email      string
	Name       string
	PictureUrl *string
	CreatedAt  time.Time
}
