// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID
	GoogleSub  string
	Email      string
	Name       string
	PictureUrl *string
	CreatedAt  time.Time
}
