// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package auth

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAuthCode = `-- name: ConsumeAuthCode :one
delete from auth_codes
where code_hash = $1 and expires_at > now()
returning user_id, redirect
`

type ConsumeAuthCodeRow struct {
	UserID   uuid.UUID
	Redirect string
}

func (q *Queries) ConsumeAuthCode(ctx context.Context, codeHash []byte) (ConsumeAuthCodeRow, error) {
	row := q.db.QueryRow(ctx, consumeAuthCode, codeHash)
	var i ConsumeAuthCodeRow
	err := row.Scan(&i.UserID, &i.Redirect)
	return i, err
}

const createAuthCode = `-- name: CreateAuthCode :exec
insert into auth_codes (code_hash, user_id, redirect, expires_at)
values ($1, $2, $3, $4)
`

type CreateAuthCodeParams struct {
	CodeHash  []byte
	UserID    uuid.UUID
	Redirect  string
	ExpiresAt time.Time
}

func (q *Queries) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createAuthCode,
		arg.CodeHash,
		arg.UserID,
		arg.Redirect,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
insert into sessions (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredAuthCodes = `-- name: DeleteExpiredAuthCodes :exec
delete from auth_codes where expires_at <= now()
`

func (q *Queries) DeleteExpiredAuthCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthCodes)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
delete from sessions where expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const extendSession = `-- name: ExtendSession :exec
update sessions set expires_at = $2 where token_hash = $1
`

type ExtendSessionParams struct {
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
select users.id, users.google_sub, users.email, users.name, users.picture_url, users.created_at, sessions.expires_at
from sessions
join users on users.id = sessions.user_id
where sessions.token_hash = $1 and sessions.expires_at > now()
`

type GetSessionUserRow struct {
	User      User
	ExpiresAt time.Time
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.GoogleSub,
		&i.User.Email,
		&i.User.Name,
		&i.User.PictureUrl,
		&i.User.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
insert into users (google_sub, email, name, picture_url)
values ($1, $2, $3, $4)
on conflict (google_sub) do update
set email = excluded.email, name = excluded.name, picture_url = excluded.picture_url
returning id, google_sub, email, name, picture_url, created_at
`

type UpsertUserParams struct {
	GoogleSub  string
	Email      string
	Name       string
	PictureUrl *string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
	)
	return i, err
}
