name: api

on:
  pull_request:
    paths: ["apps/api/**", ".github/workflows/api.yml"]
  push:
    branches: [main]
    paths: ["apps/api/**", ".github/workflows/api.yml"]

defaults:
  run:
    working-directory: apps/api

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: apps/api/go.mod
          cache-dependency-path: apps/api/go.sum
      - uses: sqlc-dev/setup-sqlc@c0209b9199cd1cce6a14fc27cabcec491b651761 # v4.0.0
        with:
          sqlc-version: "1.30.0"
      - run: go build -o bin/ ./...
      - run: go generate ./... && git diff --exit-code
      - run: go test -p 1 ./...
      - run: go run golang.org/x/vuln/cmd/govulncheck@v1.6.0 ./...
      - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          working-directory: apps/api
