package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/do-indeksa/platform/apps/api/internal/graph/model"
	"github.com/do-indeksa/platform/apps/api/internal/progress"
)

// StartRun is the resolver for the startRun field.
func (r *mutationResolver) StartRun(ctx context.Context, input model.StartRunInput) (*model.Run, error) {
	user, err := requestUser(ctx)
	if err != nil {
		return nil, err
	}
	domainInput, err := progressStartRunInput(input)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	aggregate, err := r.progress.StartRun(ctx, user.ID, domainInput)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	result, err := graphRun(aggregate)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	return result, nil
}

// RecordAttempt is the resolver for the recordAttempt field.
func (r *mutationResolver) RecordAttempt(ctx context.Context, input model.RecordAttemptInput) (*model.Attempt, error) {
	user, err := requestUser(ctx)
	if err != nil {
		return nil, err
	}
	domainInput, err := progressRecordAttemptInput(input)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	attempt, err := r.progress.RecordAttempt(ctx, user.ID, domainInput)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	result, err := graphAttempt(attempt, nil)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	return &result, nil
}

// SubmitRun is the resolver for the submitRun field.
func (r *mutationResolver) SubmitRun(ctx context.Context, input model.SubmitRunInput) (*model.Run, error) {
	user, err := requestUser(ctx)
	if err != nil {
		return nil, err
	}
	domainInput, err := progressSubmitRunInput(input)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	aggregate, err := r.progress.SubmitRun(ctx, user.ID, domainInput)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	result, err := graphRun(aggregate)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	return result, nil
}

// Run is the resolver for the run field.
func (r *queryResolver) Run(ctx context.Context, id string) (*model.Run, error) {
	user, err := requestUser(ctx)
	if err != nil {
		return nil, err
	}
	runID, err := inputID(id, "id")
	if err != nil {
		return nil, presentError(ctx, err)
	}
	aggregate, err := r.progress.GetRun(ctx, user.ID, runID)
	if errors.Is(err, progress.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, presentError(ctx, err)
	}
	result, err := graphRun(aggregate)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	return result, nil
}

// Runs is the resolver for the runs field.
func (r *queryResolver) Runs(ctx context.Context, limit int32) ([]model.RunSummary, error) {
	user, err := requestUser(ctx)
	if err != nil {
		return nil, err
	}
	runs, err := r.progress.ListRuns(ctx, user.ID, limit)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	result := make([]model.RunSummary, len(runs))
	for i, run := range runs {
		result[i], err = graphRunSummary(run)
		if err != nil {
			return nil, presentError(ctx, err)
		}
	}
	return result, nil
}

// RecentAttempts is the resolver for the recentAttempts field.
func (r *runItemResolver) RecentAttempts(ctx context.Context, obj *model.RunItem, limit int32) ([]model.Attempt, error) {
	if limit < 1 || limit > progress.MaxRecentRunItemAttempts {
		return nil, presentError(ctx, invalidGraphInput("limit"))
	}
	if len(obj.RecentAttempts) <= int(limit) {
		return obj.RecentAttempts, nil
	}
	return obj.RecentAttempts[len(obj.RecentAttempts)-int(limit):], nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// RunItem returns RunItemResolver implementation.
func (r *Resolver) RunItem() RunItemResolver { return &runItemResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	runItemResolver  struct{ *Resolver }
)
