package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"github.com/do-indeksa/platform/apps/api/internal/graph/model"
)

// StartRun is the resolver for the startRun field.
func (r *mutationResolver) StartRun(ctx context.Context, input model.StartRunInput) (*model.Run, error) {
	panic(fmt.Errorf("not implemented: StartRun - startRun"))
}

// RecordAttempt is the resolver for the recordAttempt field.
func (r *mutationResolver) RecordAttempt(ctx context.Context, input model.RecordAttemptInput) (*model.Attempt, error) {
	panic(fmt.Errorf("not implemented: RecordAttempt - recordAttempt"))
}

// SubmitRun is the resolver for the submitRun field.
func (r *mutationResolver) SubmitRun(ctx context.Context, input model.SubmitRunInput) (*model.Run, error) {
	panic(fmt.Errorf("not implemented: SubmitRun - submitRun"))
}

// Run is the resolver for the run field.
func (r *queryResolver) Run(ctx context.Context, id string) (*model.Run, error) {
	panic(fmt.Errorf("not implemented: Run - run"))
}

// Runs is the resolver for the runs field.
func (r *queryResolver) Runs(ctx context.Context, limit int32) ([]model.RunSummary, error) {
	panic(fmt.Errorf("not implemented: Runs - runs"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
