package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/do-indeksa/platform/apps/api/internal/graph/model"
	"github.com/do-indeksa/platform/apps/api/internal/prep"
)

// SavePrepPreferences is the resolver for the savePrepPreferences field.
func (r *mutationResolver) SavePrepPreferences(ctx context.Context, input model.SavePrepPreferencesInput) (*model.PrepPreferences, error) {
	user, err := requestUser(ctx)
	if err != nil {
		return nil, err
	}
	preferences, err := r.prep.Save(ctx, user.ID, prep.SaveInput{
		ExpectedVersion: input.ExpectedVersion,
		GoalPoints:      input.GoalPoints,
		ExamDate:        input.ExamDate,
	})
	if err != nil {
		return nil, presentError(ctx, err)
	}
	return graphPrepPreferences(preferences), nil
}

// PrepPreferences is the resolver for the prepPreferences field.
func (r *queryResolver) PrepPreferences(ctx context.Context) (*model.PrepPreferences, error) {
	user, err := requestUser(ctx)
	if err != nil {
		return nil, err
	}
	preferences, err := r.prep.Get(ctx, user.ID)
	if errors.Is(err, prep.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, presentError(ctx, err)
	}
	return graphPrepPreferences(preferences), nil
}
