package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/do-indeksa/platform/apps/api/internal/graph/model"
	"github.com/do-indeksa/platform/apps/api/internal/training"
)

// SaveTrainingBuilderDraft is the resolver for the saveTrainingBuilderDraft field.
func (r *mutationResolver) SaveTrainingBuilderDraft(ctx context.Context, input model.SaveTrainingBuilderDraftInput) (*model.TrainingBuilderDraft, error) {
	user, err := requestUser(ctx)
	if err != nil {
		return nil, err
	}
	domainInput, err := trainingSaveBuilderDraftInput(input)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	draft, err := r.training.SaveBuilderDraft(ctx, user.ID, domainInput)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	result, err := graphTrainingBuilderDraft(draft)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	return result, nil
}

// TrainingBuilderDraft is the resolver for the trainingBuilderDraft field.
func (r *queryResolver) TrainingBuilderDraft(ctx context.Context) (*model.TrainingBuilderDraft, error) {
	user, err := requestUser(ctx)
	if err != nil {
		return nil, err
	}
	draft, err := r.training.GetBuilderDraft(ctx, user.ID)
	if errors.Is(err, training.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, presentError(ctx, err)
	}
	result, err := graphTrainingBuilderDraft(draft)
	if err != nil {
		return nil, presentError(ctx, err)
	}
	return result, nil
}
