// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package prep

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPreferences = `-- name: CreatePreferences :one
insert into prep_preferences (user_id, goal_points, exam_date)
values ($1, $2, $3::date)
on conflict (user_id) do nothing
returning goal_points,
          exam_date::text as exam_date,
          version,
          updated_at
`

type CreatePreferencesParams struct {
	UserID     uuid.UUID
	GoalPoints int16
	ExamDate   pgtype.Date
}

type CreatePreferencesRow struct {
	GoalPoints int16
	ExamDate   string
	Version    int64
	UpdatedAt  time.Time
}

func (q *Queries) CreatePreferences(ctx context.Context, arg CreatePreferencesParams) (CreatePreferencesRow, error) {
	row := q.db.QueryRow(ctx, createPreferences, arg.UserID, arg.GoalPoints, arg.ExamDate)
	var i CreatePreferencesRow
	err := row.Scan(
		&i.GoalPoints,
		&i.ExamDate,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreferences = `-- name: GetPreferences :one
select goal_points,
       exam_date::text as exam_date,
       version,
       updated_at
from prep_preferences
where user_id = $1
`

type GetPreferencesRow struct {
	GoalPoints int16
	ExamDate   string
	Version    int64
	UpdatedAt  time.Time
}

func (q *Queries) GetPreferences(ctx context.Context, userID uuid.UUID) (GetPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getPreferences, userID)
	var i GetPreferencesRow
	err := row.Scan(
		&i.GoalPoints,
		&i.ExamDate,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePreferences = `-- name: UpdatePreferences :one
update prep_preferences
set goal_points = $1,
    exam_date = $2::date,
    version = version + 1,
    updated_at = now()
where user_id = $3
  and version = $4
  and version < 9223372036854775807
returning goal_points,
          exam_date::text as exam_date,
          version,
          updated_at
`

type UpdatePreferencesParams struct {
	GoalPoints      int16
	ExamDate        pgtype.Date
	UserID          uuid.UUID
	ExpectedVersion int64
}

type UpdatePreferencesRow struct {
	GoalPoints int16
	ExamDate   string
	Version    int64
	UpdatedAt  time.Time
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) (UpdatePreferencesRow, error) {
	row := q.db.QueryRow(ctx, updatePreferences,
		arg.GoalPoints,
		arg.ExamDate,
		arg.UserID,
		arg.ExpectedVersion,
	)
	var i UpdatePreferencesRow
	err := row.Scan(
		&i.GoalPoints,
		&i.ExamDate,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
